[package]
name = "sleitnick/shake"
description = "Shake class for making things shake"
version = "1.0.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json", "**/*.ts"]
