gitRepoUrl = "https://github.com/Sleitnick/RbxUtil"

[[classOrder]]
classes = ["Signal", "TableUtil", "Component"]

[[classOrder]]
section = "Input"
classes = ["Input", "PreferredInput", "Keyboard", "Mouse", "Touch", "Gamepad"]

[[classOrder]]
section = "Remote Comm"
classes = ["Comm", "ServerComm", "ClientComm", "RemoteSignal", "ClientRemoteSignal", "RemoteProperty", "ClientRemoteProperty"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Utility modules for Roblox"
