[[classOrder]]
classes = ["Signal", "TableUtil", "Component"]

[[classOrder]]
section = "Input"
classes = ["Input", "PreferredInput", "Keyboard", "Mouse", "Touch"]

# [[classOrder]]
# section = "Remote"
# classes = ["Remote", "RemoteSignal", "RemoteProperty", "ClientRemoteSignal", "ClientRemoteProperty"]

[[classOrder]]
section = "Remote Comm"
classes = ["Comm", "ServerComm", "ClientComm", "RemoteSignal", "ClientRemoteSignal"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Utility modules for Roblox"
