[package]
name = "jisham318/input"
description = "Basic input classes"
version = "2.2.1"
license = "MIT"
authors = ["Stephen Leitnick", "Jacob Isham"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1"
Trove = "sleitnick/trove@0.4"
