[package]
name = "sleitnick/component"
description = "Component class"
version = "1.0.5"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^1.0"
TableUtil = "sleitnick/table-util@^1.0"
Janitor = "howmanysmall/janitor@^1.13"
Promise = "evaera/promise@^3.1"
