[package]
name = "sleitnick/component"
description = "Component class"
version = "1.0.3"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@1.0.1"
TableUtil = "sleitnick/table-util@1.0.1"
Janitor = "howmanysmall/janitor@1.13.12"
Promise = "evaera/promise@3.1.0"
