[package]
name = "sleitnick/concur"
description = "Concurrent task handler"
version = "0.1.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
