name: Docs

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i -g moonwave@latest
      - run: moonwave build --publish --code packages
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
